# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 04:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ssoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('ssoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('expires', models.BigIntegerField(default=ssoapp.models.VerifyEmail.expires_default)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'That email is already registered.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
    ]
